### ISSUE TITLE
I want to run these methods on Chinese datasets

### ISSUE THREAD

**Issue by Alternate-D** [Yueeeeeeee/Self-Supervised-QA#1]
Hello! Mr. Yue, you just provided the English QA datasets with question classes (via TREC question classification) and the question classification model. So could you please tell me what should I do to obtain the files named infersent1.pkl and qc4qa_model.pth when I run qc4qa.py on Chinese datasets like CMRC2018?

**Comment by Yueeeeeeee** [comment]
Hi since Infersent and TREC are both in English, I think you may want to use Chinese question classification datasets or use a machine translation model to first translate the questions to English. Infersent can be found at https://dl.fbaipublicfiles.com/senteval/infersent/infersent1.pkl, and our qc4qa model is provided here: https://drive.google.com/drive/folders/10JPidO9bJwM1FyuEmlNfvaPx3loZNVt8

**Comment by Alternate-D** [comment]
Ok, thanks very much!
